---
title: South American Defense Council's actions (2009-2016) - a database
author: Thales Carvalho
date: '2021-03-01'
slug: the-south-american-defense-council-s-actions-2009-2016
categories: []
tags:
  - South American Defense Council
  - Defense Policy
  - International Security
  - Policy Diffusion
  - UNASUR
  - Latin America
subtitle: ''
summary: ''
authors: []
lastmod: '2021-02-28T12:18:42-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
runtime: shiny
---

How did the South American Defense Council (SADC) act? Although SADC ceased its actions in the past years, it is still essential to learn lessons from its performance in order to improve our understanding of the regional security dynamics and, eventually, to be applied in future initiatives. Some scholars already tried to answer this question, focusing on specific examples such as the confidence-building measures, especially the standard methodology to report SADC members’ military expenditures (Saint-Pierre and Palacios Junior, 2014), exchanging information about Peace Operations and Defense Industry (Bragatti, 2019), or the role of seminars towards building a common South American identity on security and defense issues (Vitelli, 2017).

In order to contribute to this research agenda, I built a new database, including all initiatives proposed within SADC meetings. Based on the meeting records, formerly available on the UNASUR website, I detected initiatives included in Action Plans and included each of them in a row. An aggregate visualization of this database is available below, as well as the codification rules.

<iframe height="900" width="100%" frameborder="no" src="https://tlcarvalho.shinyapps.io/SADC_data/"> </iframe>

*Codification rules:*

**Axis - SADC’s initiatives were divided into four axes of action: (1) Defense Policies, (2) Military Cooperation, Humanitarian Action, and Peace Operations, (3) Defense Industry, and (4) Education and Capacity Building. I also included a fifth axis, based on initiatives conducted by the Center for Strategic Defense Studies (CEED);**

**Leader - which country (or CEED) was responsible for the initiative;**

**Proposition - the Action Plan in which each initiative was proposed;**

**Result - if the initiative was implemented (e.g., if the seminars happened) or not (i.e., if it failed to be put in practice), merged with another initiative, or transferred to another UNASUR council;**

**Outcome - based on my own codification on SADC meeting records, I inferred what each initiative was intended to implement (e.g., a seminar, a course, a policy);**

**Issue - based on my own codification on SADC meeting records, I inferred to what subject each initiative was related (e.g., building a common identity on security and defense issues, confidence-building, Peace Operations).**

Some preliminary conclusions about these data will be presented in [this upcoming talk](https://tlcarvalho.netlify.app/talk/policy_diffusion/), as well as in the related article, to be published in the International Conference on Policy Difusion and Development Cooperation’s ebook. The entire database will be available soon.

**REFERENCES**

Bragatti, M.C., 2019. Diez años del Consejo de Defensa Sudamericano: arquitectura de seguridad internacional regional. Geopolíticas Rev. Estud. Sobre Espac. Poder 10, 69–86. https://doi.org/10.5209/GEOP.59777

Saint-Pierre, H., Palacios Junior, A., 2014. As medidas de confiança do Conselho de Defesa Sul-Americano (CDS): análise dos gastos em defesa (2009-2012). Rev. Bras. Política Int. 57, 22–39

Vitelli, M., 2017. The South American Defense Council: the Building of a Community of Practice for Regional Defense. Rev. Bras. Política Int. 60, 1–17.
